# Generated by Django 4.0.4 on 2022-05-16 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 8, 36, 55, 971266, tzinfo=utc)),
        ),
    ]
