# Generated by Django 4.0.4 on 2022-05-16 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='second_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 9, 11, 23, 906370, tzinfo=utc)),
        ),
    ]
