# Generated by Django 4.0.4 on 2022-05-16 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_newuser_second_name_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 11, 29, 32, 468238, tzinfo=utc)),
        ),
    ]
