# Generated by Django 4.0.4 on 2022-06-19 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 11, 39, 32, 322087, tzinfo=utc)),
        ),
    ]
