# Generated by Django 4.0.5 on 2022-07-07 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 18, 9, 45, 386457, tzinfo=utc)),
        ),
    ]
