# Generated by Django 4.0.5 on 2022-07-07 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 19, 41, 21, 397157, tzinfo=utc)),
        ),
    ]
