# Generated by Django 4.0.4 on 2022-05-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productspecification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productspecification',
            table='Product Specification',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.CharField(blank=True, help_text='Not required', max_length=255, verbose_name='Description')),
                ('regular_price', models.IntegerField(help_text='Price in USh 🇺🇬', verbose_name='Regular Price')),
                ('discount_price', models.IntegerField(help_text='Price in USh 🇺🇬', verbose_name='Discount Price')),
                ('is_acitve', models.BooleanField(default=True, help_text='Change product Visibility', verbose_name='Product Visibility')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.producttype')),
            ],
        ),
    ]
