# Generated by Django 4.0.4 on 2022-05-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productspecification_table_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
        migrations.AlterModelTable(
            name='productspecification',
            table=None,
        ),
    ]
