# Generated by Django 4.0.4 on 2022-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productspecificationvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/logo.png', help_text='Upload a product image', upload_to='images/', verbose_name='image')),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
    ]
