# Generated by Django 4.0.5 on 2022-07-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('paymentMethod', models.CharField(max_length=255)),
                ('itemsPrice', models.IntegerField()),
                ('taxPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('paidAt', models.DateField(auto_now=True)),
                ('deliveredAt', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
